name: PyrexPrison
version: '${project.version}'
main: io.github.lunaiskey.pyrexprison.PyrexPrison
api-version: 1.17
authors: [ Lunaiskey ]
softdepend:
  - PlaceholderAPI
description: Made for PyrexMC Prison.
commands:
  pmine:
    usage: /<command>
  tokens:
    usage: /<command>
  gems:
    usage: /<command>
  pyrexpoints:
    usage: /<command>