name: LunixPrison
version: '${project.version}'
main: io.github.lunaiskey.lunixprisons.LunixPrison
api-version: 1.17
authors: [ Lunaiskey ]
description: Yet another prison plugin.
commands:
  mine:
    usage: /<command>
  mineadmin:
    usage: /<command>
  pmine:
    usage: /<command>
