name: PyrexPrison
version: '${project.version}'
main: io.github.lunaiskey.pyrexprison.PyrexPrison
api-version: 1.17
authors: [ Lunaiskey ]
description: Yet another prison plugin.
commands:
  #mine:
  #  usage: /<command>
  pmine:
    usage: /<command>
