name: LunixPrisons
version: '${project.version}'
main: io.github.lunaiskey.lunixprison.LunixPrison
api-version: 1.19
authors: [ Lunaiskey ]
softdepend:
  - PlaceholderAPI
description: A Continuation of the old PyrexPrison plugin.

commands:
  gang:
    usage: /<command>
  pmine:
    usage: /<command>
  tokens:
    usage: /<command>
  gems:
    usage: /<command>
  gemstones:
    usage: /<command>
    aliases:
      - gemstone
  lunixpoints:
    usage: /<command>
  enchants:
    usage: /<command>
    aliases: [enchant]
  rankup:
    usage: /<command>
  rankupmax:
    usage: /<command>
    aliases:
      - maxrankup
  armor:
    usage: /<command>
  getpickaxe:
    usage: /<command>
  multiplier:
    usage: /<command>
    aliases:
      - multi
  litem:
    usage: /<command>
  viewplayer:
    usage: /<command>
  rank:
    usage: /<command>
  resetpickaxe:
    usage: /<command>
  booster:
    usage: /<command>
    aliases:
      - boosters
  leaderboard:
    usage: /<command>
    aliases:
      - leaderboards
      - lb
  cashback:
    usage: /<command>
    aliases:
      - cb
  settings:
    usage: /<command>
  namecolor:
    usage: /<command>
  chatcolor:
    usage: /<command>
  lunixdebug:
    usage: /<command>

permissions:
  lunix.*:
    description: Gives access to every command.
    children:
      lunix.tokens.give: true
      lunix.tokens.take: true
      lunix.tokens.set: true
      lunix.gems.give: true
      lunix.gems.take: true
      lunix.gems.set: true
      lunix.points.give: true
      lunix.points.take: true
      lunix.points.set: true
      lunix.debug: true
      lunix.resetcooldown.bypass: true
      lunix.admin.getitem: true
  lunix.tokens.give:
    description: Give Tokens to players.
  lunix.tokens.take:
    description: Take Tokens from players.
  lunix.tokens.set:
    description: Set a players Tokens.
  lunix.gems.give:
    description: Give Gems to players.
  lunix.gems.take:
    description: Take Gems from players.
  lunix.gems.set:
    description: Set a players Gems.
  lunix.points.give:
    description: Give LunixPoints to players.
  lunix.points.take:
    description: Take LunixPoints from players.
  lunix.points.set:
    description: Set a players LunixPoints.
  lunix.debug:
    description: Gives access to debug commands.
  lunix.resetcooldown.bypass:
    description: Bypass private mine reset cooldown.